sudo: required
services:
  - docker

before_install:
  - docker build -t mariusble/docker-react -f Dockerfile.dev .

script:
#  - docker run mariusble/docker-react npm run test -- --coverage
  - docker run -e CI=true mariusble/docker-react npm run test 
